### ISSUE TITLE
Founding Platinum vs. Platinum members

### ISSUE THREAD

**Issue by cuviper** [rustfoundation/foundation.rust-lang.org#102]
On the members page, I think it's misleading to list "Founding Platinum" and "Platinum" members separately, as if they have some ongoing distinction in the foundation. Maybe instead we could list them together, but with some sort of "founding" badge?

**Comment by abibroom** [comment]
I'm thinking I might try a rollover effect like with people's Ferris drawings, to reveal:
![founding-member-f46623](https://user-images.githubusercontent.com/560001/159081692-df6fae7c-5b54-472d-a0a4-aa34227b9509.jpg)
![founding-member-ffa83d](https://user-images.githubusercontent.com/560001/159081698-f4ca3254-ae5c-4b1f-8ecb-43866dcfb898.jpg)
The darker orange is probably my preference? Not sure. Might change my mind in situ.

**Comment by cuviper** [comment]
A rollover sounds nice too. That could also be adapted for other members to show something like "Since DATE". (by month?)

**Comment by tmandry** [comment]
Venturing pretty far outside my expertise here, personally I favor a simpler "static" approach which makes the content more accessible. Something like this can work too, but aesthetically I'm not sure I like the idea of replacing non-rectangle logos with orange rectangles on mouseover.

(Only posting this because I interpreted your comment as soliciting feedback, don't let me get in your way :) )

**Comment by abibroom** [comment]
Thanks @tylermandry and of course I wouldn't have left a comment if I wasn't inviting feedback :)

I also don't think this is the best solution for accessibility, but the thing I wasn't sure about with adding a badge to the logos _themselves_ is whether we'd need to run that past members' marketing/comms departments to gain approval - big corporates tend to be a little touchy about that kind of thing and have strict logo usage policies.

I _also_ also might go off the orange background idea entirely, if it looks awful in practice. White/transparent may be better.
