### ISSUE TITLE
Members page still includes old "Facebook" logo

### ISSUE THREAD

**Issue by Aloso** [rustfoundation/foundation.rust-lang.org#121]
The members page contains this outdated logo:

![2021-11-19 17_43_51-Rust Foundation - Rust Foundation - Firefox Developer Edition](https://user-images.githubusercontent.com/15658558/142659789-0cee8eba-b9f1-4527-8732-8ba38c4a86f4.png)

The new logo is this:

![Meta_lockup_primary_RGB](https://user-images.githubusercontent.com/15658558/142659575-f2a9e83a-eb71-4b8e-b34b-29d13bb530be.png)

See https://about.fb.com/news/2021/10/facebook-company-is-now-meta/

**Comment by JoelMarcey** [comment]
This has been updated. Thanks.
