### ISSUE TITLE
Secure connection failed

### ISSUE THREAD

**Issue by Bassetts** [rustfoundation/foundation.rust-lang.org#207]
I am getting a secure connection failed error (SEC_ERROR_OCSP_SERVER_ERROR) in Firefox 101.0a1 (2022-04-12) (64-bit) when I have HTTPS-Only Mode enabled. Adding a temporary exception for `https://foundation.rust-lang.org` stops the error.

**Comment by JoelMarcey** [comment]
Hmmmm... interesting. I am running what Firefox says is the latest. 99.0.1. I guess you are using an alpha/beta version ? It seems to load for me. I am running on a Mac OS 12.2.1. I can't imagine it is an operating system issue though.

<img width="756" alt="Screen Shot 2022-04-13 at 3 12 14 PM" src="https://user-images.githubusercontent.com/3757713/163278967-6944600e-175d-4aae-abdb-d9f85a4da9d1.png">

<img width="656" alt="Screen Shot 2022-04-13 at 3 12 02 PM" src="https://user-images.githubusercontent.com/3757713/163278970-fc26d15b-beb7-486d-aa27-3f9c630160f3.png">

<img width="1184" alt="Screen Shot 2022-04-13 at 3 12 25 PM" src="https://user-images.githubusercontent.com/3757713/163278964-0bcafab2-9466-489f-9b54-1e5688bcf945.png">

**Comment by Bassetts** [comment]
I am using Firefox Nightly, it seems to be related to the fact I am using [arkenfox user.js](https://github.com/arkenfox/user.js) as I have just tried on a profile without arkenfox and it worked. This was on a different machine though. I will try and do some digging and see if I can figure out what setting(s) is causing the error.

**Comment by Bassetts** [comment]
I have just tried again on the same machine and profile that was failing when I raised the ticket and strangely I cannot reproduce this anymore. I am wondering if there was an issue with the OCSP when I tried earlier. I will close the ticket for now and keep an eye out for any further issues.
