### ISSUE TITLE
Staff entry for Jan David

### ISSUE THREAD

**Issue by cuviper** [rustfoundation/foundation.rust-lang.org#262]
Jan David needs a Staff entry on the About page -- and don't forget the crab! -- but in the meantime the blog announcement (#261) is holding his place due to the "staff" tag.

![image](https://user-images.githubusercontent.com/36186/189741396-4e4b175a-76a3-4e95-95c5-0d44bcda88d9.png)

**Comment by abibroom** [comment]
I added a pic but didn't yet have a crab to hand, so leaving this open for now.

**Comment by cuviper** [comment]
Thanks! It's up to you whether the crab should actually be required -- others are still missing that too. :)

**Comment by JoelMarcey** [comment]
Added...
